spring.application.name=API
# URL de conexão (substitua 'seu_banco_de_dados' pelo nome do seu schema)
spring.datasource.url=jdbc:mysql://localhost:3306/db_api?useSSL=false&serverTimezone=UTC

# Credenciais de acesso ao MySQL
spring.datasource.username=root
spring.datasource.password=

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
# 'update' atualiza a estrutura do banco automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update
# Exibe as consultas SQL geradas no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
